services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  schemalabui:
    image: nginx:alpine
    env_file:
      - ./schemalab-ui/.env.production
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        
  schema:
    image: nginx:alpine
    env_file:
      - ./schemalab-ui/.env.production.local
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
  management:
    image: nginx:alpine
    env_file:
      - ./management/.env.production
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
  management_db:
    image: postgres:16
    env_file:
      - ./management/.env.production
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - management_pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

auth:
    image: nginx:alpine
    command: >
      sh -c "sleep 5 && 
             python manage.py migrate --no-input && 
             python manage.py runserver 0.0.0.0:5050"
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

auth_db:
  image: postgres:14-alpine
  environment:
    - POSTGRES_USER=myuser
    - POSTGRES_PASSWORD=mypassword
    - POSTGRES_DB=auth_db
  volumes:
    - auth_db_data_prod:/var/lib/postgresql/data
  networks:
    - app-network
  deploy:
    restart_policy:
      condition: on-failure

networks:
  app-network:
    driver: overlay