services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  schemalabui:
    image: nginx:alpine
    env_file:
      - ./schemalab-ui/.env.production
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        
  schema:
    image: nginx:alpine
    env_file:
      - ./schemalab-ui/.env.production.local
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay